### ISSUE TITLE
cdom_gaussian

### ISSUE THREAD

**Issue by Nawalbouchachi** [PMassicotte/cdom#15]
Hello I have installed the cdom package but seems that it does not include the cdom_gaussian function. Can you with this ?

#devtools::install_github("PMassicotte/cdom")
library(cdom)

ls("package:cdom")
[1] "cdom_exponential"    "cdom_slope_ratio"    "cdom_spectral_curve" "spectra"

**Comment by PMassicotte** [comment]
In it currently implemented in branch: https://github.com/PMassicotte/cdom/tree/gaussian. Still experimental.
