### ISSUE TITLE
Input parameter to the cdom_fit_exponential. Absorbance or absorption?

### ISSUE THREAD

**Issue by lisapro** [PMassicotte/cdom#17]
Hello, 
I have a question regarding the cdom_fit_exponential function. 

In the description of the package it is said: "Wrapper functions to model and extract various quantitative information from absorption spectra of chromophoric dissolved organic matter (CDOM)" 

But the input parameter for the cdom_fit_exponential is absorbance, not absorption. Since the cuvette length is not a parameter, I assume there is no conversion from the absorbance to absorption within the function. 

```
  fit <- cdom_fit_exponential(wl = spectra$wavelength,
                         absorbance = spectra$spc3,
                         wl0 = 350,
                         startwl = 190,
                         endwl = 900)
```

So, I am a bit confused. What does the function return? fit from absorbance spectra? Or is it a typo, and the user should send absorption as a parameter to the cdomt_fit_exponential? 

I am quite new in the cDOM topic,  so I could have misunderstood something, would appreciate your answer and clarification.

**Comment by PMassicotte** [comment]
Hi @lisapro.

You can fit either absorption or absorbance. You can convert absorbance to absorption before the fit or after the fit. Does it help?

**Comment by lisapro** [comment]
Hi. Then it just means that there is no restriction on what to send to the function as a parameter? Yes, it helps, thanks! I guess it would be helpful for others as well to have it mentioned in the documentation :)

**Comment by PMassicotte** [comment]
You are right!
