### ISSUE TITLE
Problem to unnest model after cdom_exponential function

### ISSUE THREAD

**Issue by LcsTsd** [PMassicotte/cdom#18]
Hi, 

I'm using your package to analyze some CDOM data and I encounter a problem after using the cdom_exponential function as follows :

```
data(spectra)
spectra <- spectra %>%
gather(sample, absorption, starts_with("spc")) %>% 
  group_by(sample) %>% 
  nest() %>% 
  mutate(model = purrr::map(data, ~cdom_exponential(.$wavelength, .$absorption, wl0 = 350, startwl = 190, endwl = 900)))

spectra %>% unnest(model %>% purrr::map(~.$data$.fitted))
```
The function works well until the moment where I want to unnest the model to get back the coefficients for the different groups.
After running the last command, I obtain the following issue (with the example dataset as well as with my own data) :
```
Error: object 'model' not found
Run `rlang::last_error()` to see where the error occurred.
```
I don't know if this error is due to some changes in the dependencies of the package, so I would like to have your opinion on what could be the cause of this error.

Thank you for your help!

**Comment by PMassicotte** [comment]
What looks like `spectra` after you `map` the exponential function?

**Comment by LcsTsd** [comment]
Spectra looks like this :
![image](https://user-images.githubusercontent.com/47827148/144443837-7bbf8b0b-ae30-4cae-b49c-e38851d5fda7.png)

**Comment by LcsTsd** [comment]
I have another question concerning the K parameter in the cdom_exponential function. I saw in another topic you suggested modifying the function to remove this parameter. Is this still necessary or not ?

Thank you for your reply.

**Comment by PMassicotte** [comment]
Maybe the problem is there `spectra %>% unnest(model %>% purrr::map(~.$data$.fitted))` hard to tell without the data. For `K`, you can use it as a fit parameter or not consider it if you manually subtract background (mean average at higher wavelength).

**Comment by LcsTsd** [comment]
Thank you for your reply!
I also have the same problem with the `spectra` dataset so you should be able to reproduce the error unless it comes from my side. In any case, I found another way to get back the slope coefficients.

Thank you for the advice. Indeed, I already subtracted the mean average between 683 and 687 nm.

**Comment by PMassicotte** [comment]
Works fine on my side to extract the params.

```r
spectra %>% 
  pivot_longer(contains("spc")) %>% 
  group_nest(name) %>% 
  mutate(mod = map(data, ~cdom_fit_exponential(.$wavelength, .$value, 350, 190, 900))) %>% 
  mutate(tidied = map(mod, ~.$params))
```
